version: '2'
services:
    ada-app:
        image: ada
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ada-mysql:3306/ada?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ada-mysql:
        extends:
            file: mysql.yml
            service: ada-mysql
